### ISSUE TITLE
TAF valid time

### ISSUE THREAD

**Issue by ibazar83** [fmidev/fmi-avi-messageconverter-tac#24]
Hi,
in fi.fmi.avi.converter.tac.lexer.impl.token.ValidTime.getAsLexeme, taf.getValidityTime() should be changed to taf.getReferredReport().getValidityTime() when TAF status is equal to CANCELLATION or AMENDMENT or CORRECTION

Thanks

**Comment by ilkkarinne** [comment]
Indeed, this will be fixed in the next release

**Comment by ilkkarinne** [comment]
Note: I will still use the taf.getValidTime() for AMENDMENT, because the TAC AMD message valid time may differ for the valid time of the amended original TAF. CORRECTION and CANCELLATION should use taf.getReferredReport().getValidityTime() instead.

This change should also affect the TAF parsing: the referredReport (including the valid time) should be created for CORRECTION and CANCELLATION messages when parsing, and the valid time left empty for the primary TAF object in these cases.

**Comment by ilkkarinne** [comment]
Fixed with 1d78b959fc26737c0e5c0129cdce22b33fb3619f

**Comment by ilkkarinne** [comment]
Reopening this, it seems that there are local variation of how the mapping between the TAC encoded TAF valid time and the TAF POJO validityTime vs. referredReport/validityTime should be mapped. 

I will now implement the mapping to referredReport/validityTime for CORRECTION, CANCELLATION and AMENDMENT by default, and add a ConversionHint to control this to work otherwise, see https://github.com/fmidev/fmi-avi-messageconverter/blob/4a89960f1c9442faff1a3584d9b46c3017bd850a/src/main/java/fi/fmi/avi/converter/ConversionHints.java#L214-L237

**Comment by ilkkarinne** [comment]
Fixed with 2e0c2778e097cab8dd37ffb90a2aec185f89d7f4
